workflows:
  vibeplay_ios_unsigned:
    name: VibePlay+ iOS (unsigned)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_DIR: build/ios/iphoneos
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS (unsigned)
        script: |
          flutter clean
          flutter pub get
          export CODE_SIGNING_ALLOWED=NO
          flutter build ios --release --no-codesign

        

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa

    publishing:
      email:
        recipients:
          - frank.le.febre@rws.nl
